### ISSUE TITLE
Add a release method

### ISSUE THREAD

**Issue by BOTTOMFRAGGER523** [zalanwastaken/guified#1]
So i was creating a simple game, and i needed a way to make buttons only clickable for 1 time, i tried to look for a button release method but to no avail. i can give you a code snippet of i want it to look like
``` 
button.release()
```
(Sorry if i explained it poorly)

**Comment by BOTTOMFRAGGER523** [comment]
wait sorry found a bypass
```
buttonclick = true

if button.pressed() then
    if buttonclick then
        buttonclick = false
        -- Code here
    end
end
 
if not button.pressed() then
    buttonclick = true
end
```

**Comment by zalanwastaken** [comment]
Thank you for suggesting this feature! A `button.release()` method is indeed a great idea for improving button interaction handling. I understand the value it adds, especially for single-click scenarios, and I’m happy to let you know that this feature will be implemented in the next few updates. Stay tuned! 😊
